# Generated by Django 3.2 on 2023-01-01 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Оценка должна быть не меньше 0.'), django.core.validators.MaxValueValidator(10, 'Оценка должна быть не больше 10.')], verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023, 'Год создания произведения не может быть в будущем')], verbose_name='Год выпуска'),
        ),
    ]
