# Generated by Django 3.2 on 2023-01-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230101_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name', 'year'), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
